// Code generated by go-swagger; DO NOT EDIT.

package release_flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewClientConfigParams creates a new ClientConfigParams object
// with the default values initialized.
func NewClientConfigParams() *ClientConfigParams {
	var ()
	return &ClientConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewClientConfigParamsWithTimeout creates a new ClientConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewClientConfigParamsWithTimeout(timeout time.Duration) *ClientConfigParams {
	var ()
	return &ClientConfigParams{

		timeout: timeout,
	}
}

// NewClientConfigParamsWithContext creates a new ClientConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewClientConfigParamsWithContext(ctx context.Context) *ClientConfigParams {
	var ()
	return &ClientConfigParams{

		Context: ctx,
	}
}

// NewClientConfigParamsWithHTTPClient creates a new ClientConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewClientConfigParamsWithHTTPClient(client *http.Client) *ClientConfigParams {
	var ()
	return &ClientConfigParams{
		HTTPClient: client,
	}
}

/*ClientConfigParams contains all the parameters to send to the API endpoint
for the client config operation typically these are written to a http.Request
*/
type ClientConfigParams struct {

	/*Body*/
	Body ClientConfigBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the client config params
func (o *ClientConfigParams) WithTimeout(timeout time.Duration) *ClientConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the client config params
func (o *ClientConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the client config params
func (o *ClientConfigParams) WithContext(ctx context.Context) *ClientConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the client config params
func (o *ClientConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the client config params
func (o *ClientConfigParams) WithHTTPClient(client *http.Client) *ClientConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the client config params
func (o *ClientConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the client config params
func (o *ClientConfigParams) WithBody(body ClientConfigBody) *ClientConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the client config params
func (o *ClientConfigParams) SetBody(body ClientConfigBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ClientConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
