// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/toggler-io/toggler/lib/go/models"
)

// NewCreateRolloutFeatureFlagParams creates a new CreateRolloutFeatureFlagParams object
// with the default values initialized.
func NewCreateRolloutFeatureFlagParams() *CreateRolloutFeatureFlagParams {
	var ()
	return &CreateRolloutFeatureFlagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRolloutFeatureFlagParamsWithTimeout creates a new CreateRolloutFeatureFlagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRolloutFeatureFlagParamsWithTimeout(timeout time.Duration) *CreateRolloutFeatureFlagParams {
	var ()
	return &CreateRolloutFeatureFlagParams{

		timeout: timeout,
	}
}

// NewCreateRolloutFeatureFlagParamsWithContext creates a new CreateRolloutFeatureFlagParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRolloutFeatureFlagParamsWithContext(ctx context.Context) *CreateRolloutFeatureFlagParams {
	var ()
	return &CreateRolloutFeatureFlagParams{

		Context: ctx,
	}
}

// NewCreateRolloutFeatureFlagParamsWithHTTPClient creates a new CreateRolloutFeatureFlagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRolloutFeatureFlagParamsWithHTTPClient(client *http.Client) *CreateRolloutFeatureFlagParams {
	var ()
	return &CreateRolloutFeatureFlagParams{
		HTTPClient: client,
	}
}

/*CreateRolloutFeatureFlagParams contains all the parameters to send to the API endpoint
for the create rollout feature flag operation typically these are written to a http.Request
*/
type CreateRolloutFeatureFlagParams struct {

	/*Body*/
	Body *models.FeatureFlag

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) WithTimeout(timeout time.Duration) *CreateRolloutFeatureFlagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) WithContext(ctx context.Context) *CreateRolloutFeatureFlagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) WithHTTPClient(client *http.Client) *CreateRolloutFeatureFlagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) WithBody(body *models.FeatureFlag) *CreateRolloutFeatureFlagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create rollout feature flag params
func (o *CreateRolloutFeatureFlagParams) SetBody(body *models.FeatureFlag) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRolloutFeatureFlagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
