// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReleaseClientConfigParams creates a new ReleaseClientConfigParams object
// with the default values initialized.
func NewReleaseClientConfigParams() *ReleaseClientConfigParams {

	return &ReleaseClientConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReleaseClientConfigParamsWithTimeout creates a new ReleaseClientConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReleaseClientConfigParamsWithTimeout(timeout time.Duration) *ReleaseClientConfigParams {

	return &ReleaseClientConfigParams{

		timeout: timeout,
	}
}

// NewReleaseClientConfigParamsWithContext creates a new ReleaseClientConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewReleaseClientConfigParamsWithContext(ctx context.Context) *ReleaseClientConfigParams {

	return &ReleaseClientConfigParams{

		Context: ctx,
	}
}

// NewReleaseClientConfigParamsWithHTTPClient creates a new ReleaseClientConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReleaseClientConfigParamsWithHTTPClient(client *http.Client) *ReleaseClientConfigParams {

	return &ReleaseClientConfigParams{
		HTTPClient: client,
	}
}

/*ReleaseClientConfigParams contains all the parameters to send to the API endpoint
for the release client config operation typically these are written to a http.Request
*/
type ReleaseClientConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the release client config params
func (o *ReleaseClientConfigParams) WithTimeout(timeout time.Duration) *ReleaseClientConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the release client config params
func (o *ReleaseClientConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the release client config params
func (o *ReleaseClientConfigParams) WithContext(ctx context.Context) *ReleaseClientConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the release client config params
func (o *ReleaseClientConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the release client config params
func (o *ReleaseClientConfigParams) WithHTTPClient(client *http.Client) *ReleaseClientConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the release client config params
func (o *ReleaseClientConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReleaseClientConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
