// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/adamluzsi/toggler/lib/go/models"
)

// NewRolloutClientConfigParams creates a new RolloutClientConfigParams object
// with the default values initialized.
func NewRolloutClientConfigParams() *RolloutClientConfigParams {
	var ()
	return &RolloutClientConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRolloutClientConfigParamsWithTimeout creates a new RolloutClientConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRolloutClientConfigParamsWithTimeout(timeout time.Duration) *RolloutClientConfigParams {
	var ()
	return &RolloutClientConfigParams{

		timeout: timeout,
	}
}

// NewRolloutClientConfigParamsWithContext creates a new RolloutClientConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewRolloutClientConfigParamsWithContext(ctx context.Context) *RolloutClientConfigParams {
	var ()
	return &RolloutClientConfigParams{

		Context: ctx,
	}
}

// NewRolloutClientConfigParamsWithHTTPClient creates a new RolloutClientConfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRolloutClientConfigParamsWithHTTPClient(client *http.Client) *RolloutClientConfigParams {
	var ()
	return &RolloutClientConfigParams{
		HTTPClient: client,
	}
}

/*RolloutClientConfigParams contains all the parameters to send to the API endpoint
for the rollout client config operation typically these are written to a http.Request
*/
type RolloutClientConfigParams struct {

	/*Body*/
	Body *models.RolloutClientConfigRequestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the rollout client config params
func (o *RolloutClientConfigParams) WithTimeout(timeout time.Duration) *RolloutClientConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the rollout client config params
func (o *RolloutClientConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the rollout client config params
func (o *RolloutClientConfigParams) WithContext(ctx context.Context) *RolloutClientConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the rollout client config params
func (o *RolloutClientConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the rollout client config params
func (o *RolloutClientConfigParams) WithHTTPClient(client *http.Client) *RolloutClientConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the rollout client config params
func (o *RolloutClientConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the rollout client config params
func (o *RolloutClientConfigParams) WithBody(body *models.RolloutClientConfigRequestBody) *RolloutClientConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the rollout client config params
func (o *RolloutClientConfigParams) SetBody(body *models.RolloutClientConfigRequestBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RolloutClientConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
