// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClientConfigRequestInput client config request input
// swagger:model ClientConfigRequestInput
type ClientConfigRequestInput struct {

	// PilotExtID is the public uniq id that identify the caller pilot
	// Required: true
	PilotExtID *string `json:"id"`

	// ReleaseFlags are the list of private release flag name that should be matched against the pilot and state the enrollment for each.
	// Required: true
	ReleaseFlags []string `json:"release_flags"`
}

// Validate validates this client config request input
func (m *ClientConfigRequestInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePilotExtID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReleaseFlags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClientConfigRequestInput) validatePilotExtID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.PilotExtID); err != nil {
		return err
	}

	return nil
}

func (m *ClientConfigRequestInput) validateReleaseFlags(formats strfmt.Registry) error {

	if err := validate.Required("release_flags", "body", m.ReleaseFlags); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClientConfigRequestInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientConfigRequestInput) UnmarshalBinary(b []byte) error {
	var res ClientConfigRequestInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
