// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IsFeatureGloballyEnabledRequestPayload is feature globally enabled request payload
// swagger:model IsFeatureGloballyEnabledRequestPayload
type IsFeatureGloballyEnabledRequestPayload struct {

	// Feature is the Feature Flag name that is needed to be checked for enrollment
	// Required: true
	Feature *string `json:"feature"`
}

// Validate validates this is feature globally enabled request payload
func (m *IsFeatureGloballyEnabledRequestPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IsFeatureGloballyEnabledRequestPayload) validateFeature(formats strfmt.Registry) error {

	if err := validate.Required("feature", "body", m.Feature); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IsFeatureGloballyEnabledRequestPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IsFeatureGloballyEnabledRequestPayload) UnmarshalBinary(b []byte) error {
	var res IsFeatureGloballyEnabledRequestPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
