// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RolloutClientConfigResponseBody RolloutClientConfigResponseBody will contain the requested feature flag states for a certain pilot.
//
// The content expected to be cached in some form of state container.
// swagger:model RolloutClientConfigResponseBody
type RolloutClientConfigResponseBody struct {

	// States holds the requested rollout feature flag enrollment statuses.
	States map[string]bool `json:"states,omitempty"`
}

// Validate validates this rollout client config response body
func (m *RolloutClientConfigResponseBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RolloutClientConfigResponseBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RolloutClientConfigResponseBody) UnmarshalBinary(b []byte) error {
	var res RolloutClientConfigResponseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
