// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebsocketRequestPayload websocket request payload
// swagger:model WebsocketRequestPayload
type WebsocketRequestPayload struct {

	// Data content correspond with the api payloads of the given operations.
	Data interface{} `json:"data,omitempty"`

	// Operation describe the chosen operation that needs to be executed.
	// Required: true
	// Enum: [IsFeatureEnabled IsFeatureGloballyEnabled]
	Operation *string `json:"operation"`
}

// Validate validates this websocket request payload
func (m *WebsocketRequestPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var websocketRequestPayloadTypeOperationPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["IsFeatureEnabled","IsFeatureGloballyEnabled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		websocketRequestPayloadTypeOperationPropEnum = append(websocketRequestPayloadTypeOperationPropEnum, v)
	}
}

const (

	// WebsocketRequestPayloadOperationIsFeatureEnabled captures enum value "IsFeatureEnabled"
	WebsocketRequestPayloadOperationIsFeatureEnabled string = "IsFeatureEnabled"

	// WebsocketRequestPayloadOperationIsFeatureGloballyEnabled captures enum value "IsFeatureGloballyEnabled"
	WebsocketRequestPayloadOperationIsFeatureGloballyEnabled string = "IsFeatureGloballyEnabled"
)

// prop value enum
func (m *WebsocketRequestPayload) validateOperationEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, websocketRequestPayloadTypeOperationPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *WebsocketRequestPayload) validateOperation(formats strfmt.Registry) error {

	if err := validate.Required("operation", "body", m.Operation); err != nil {
		return err
	}

	// value enum
	if err := m.validateOperationEnum("operation", "body", *m.Operation); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WebsocketRequestPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebsocketRequestPayload) UnmarshalBinary(b []byte) error {
	var res WebsocketRequestPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
