// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/toggler-io/toggler/lib/go/client/pilot"
	"github.com/toggler-io/toggler/lib/go/client/release"
	"github.com/toggler-io/toggler/lib/go/client/release_flag"
)

// Default provides API on HTTP layer to the toggler service HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new provides API on HTTP layer to the toggler service HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ProvidesAPIOnHTTPLayerToTheTogglerService {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new provides API on HTTP layer to the toggler service HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *ProvidesAPIOnHTTPLayerToTheTogglerService {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new provides API on HTTP layer to the toggler service client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ProvidesAPIOnHTTPLayerToTheTogglerService {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(ProvidesAPIOnHTTPLayerToTheTogglerService)
	cli.Transport = transport
	cli.Pilot = pilot.New(transport, formats)
	cli.Release = release.New(transport, formats)
	cli.ReleaseFlag = release_flag.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// ProvidesAPIOnHTTPLayerToTheTogglerService is a client for provides API on HTTP layer to the toggler service
type ProvidesAPIOnHTTPLayerToTheTogglerService struct {
	Pilot pilot.ClientService

	Release release.ClientService

	ReleaseFlag release_flag.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ProvidesAPIOnHTTPLayerToTheTogglerService) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Pilot.SetTransport(transport)
	c.Release.SetTransport(transport)
	c.ReleaseFlag.SetTransport(transport)
}
