// Code generated by "esc -o ./views/fs.go -ignore fs.go -pkg views -prefix views ./views"; DO NOT EDIT.

package views

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/flag/create.html": {
		name:    "create.html",
		local:   "views/flag/create.html",
		size:    2085,
		modtime: 1561461063,
		compressed: `
H4sIAAAAAAAC/8xV3WrjPBC971MMuvm+vbDT9jo2lF0KC2UpXfoAE2tiC/SHNOoPIe++yHZa16TdeFmW
5iajzJlzRmcUabeTtFWWQBhUVuz3ZwAAa6keoNEYYyUaZ5ksi7rP9NnucpYsOkIJKhYNWaYg6t0Oyh9o
CPb79aq7nNROmH0KVLQT4jlAFxv3VOjQQg9N41dxMavp67YuGMCGlbOVWG01tgIMcedkJbyLLN7I9uiX
qECtWktSgETGYqP4EYMkWzwiN52ybSWOaQ66irSMxPXZ0fzRTWfbgtNFG1zy7xC/FGvckIatC5XYEnIK
JOrrIYDs8XrVI37DoqxPDEq+koBFQ5XITpU5FB8SjB9+9lQJpic+Ce41NtQ5Lem1e8iKvXhZlh9sfr2S
6uFfuOop5HOLLYn6zmntEsPty29L7Z2wTR0OA3EZOSBT+1xOcKcbH9BmXqNsJc4FGHyqxMX5+UkMD6gT
5bJPYHkkkqL+SSTBbYE7goBWOgM+UpLusFJ2yA3eLZ1ELzIa92YGmT1rLzDeJrOh8AdnPp/1Ufewq9xX
WZbwv/P5tkL95TOMRFKjonL2yqv7uxtRfxvXcHX7He7vbpa6P+P78L9wwN64VjVXXi0YTAp6+VS4U7G/
hv6L0KTIzsChBdC5h8Om/9KMNonZ2bHjmDZGzZ6jETCJCx+UwfAs6q+BkAmuNbbr1ZB8R2u9en2MjuRc
MLO3duj7yHIMdzuycr//FQAA//9nAXJTJQgAAA==
`,
	},

	"/flag/show.html": {
		name:    "show.html",
		local:   "views/flag/show.html",
		size:    4255,
		modtime: 1561465925,
		compressed: `
H4sIAAAAAAAC/8RXUYurOBR+76845GV3L6hz73MrDHQGCsNSWu7zkppTDRsTSeLQQfzvS6J2rLdVO4W9
voxOTr4k3znfd9KqYnjkEoHklEtS1wsAgCXj75AIasyKJEpalJbEfsSPZj8Gg0GGlAE3QYLSoiZxVUH4
Kmga/k1zhLpeRtmPHkAPvig1BmkPfRgggoM6BUKn4EPL9k/wfTDHzzsqnQNNLFdyRaKjoCmBHG2m2IoU
ylhysayPPr8FVPBUIruC22BzFMygvT7sQ7gsSguS5rgi/zTrErAfBa5IxhlDSeCdihLd+o7R20hDhhzR
Wokg1aosyO0t+MmCHlDAUekVKVC7nNAUSbxTQqjSwvb8v2XkQyfgmlNxdoE2OqV9GiJcFkLdrB0aq6nF
9CO8E6ohUVOZIoGcyxV5IpDT04p8f3qahdASf67Mlo1w3+3okxao6xGKlxHj7/9H7gy6YtwjMlBHsBmC
ppKpHAqDJVPdF5fNWHOee1PqF/liMt0G9nPnNxmUZX5A/VDCdu2q41lyT1VF35amoPIX1Qc5GkNTDLgU
XCKJl5GLi79FrQP+1sQzTLjhSj4X/OfujcTr9huetxv4uXu7N8cDvEel28G9qZQnzwW/I/2lFrOiqwr4
8ZZQ1xfrbzdQ15PivjKHVBVKNpLv3lMImmCmBEO9IjbjBhw1fxhISmNVDh0lIBx+lyf4UxWuFVHx1yN+
0u8qPiPu9UZfGTZeEt+By9kU6mY9gXkorVWyRTHlIeeDntsG9N6DQvOc6g8S7+k7glsHthqPqFEmaJZR
E3aDoWV0uy8vI6f1wdViwHb7PRwavwFVFfhWBOGWC2UNDKqouYdcXjwubiVR4eb9ehu5eqc5n28xZRwo
nVhzlDZ0KZvMVr8C/I7CBmGGpTtfubrcYpYRJBkm/x7UaTK8dYKXdl9Q134qshYDWafj2MWGLyeLWlLh
N3OjYlr3XMzkZFQWYxxf4/dkN+sRuIvtz4d1NTWK+4rUlhpffdwI9EP6NWhH1HpLqUOVVhWgZF325ovy
y6Kb/AkwJsEvNf2LG7rb1Isvi9i7CXQ1AJv1aKfvX8w/QRaTXb1fiYtJpVo82dGwi97YnGCzBptRCxKR
GbAKDgids0QHobxsr/n19U74MMefRkXil/M77C21pZnLcQ9kNsdz3HRgiHfQ8hUfGOvij6l/hyk3FjX4
GrhhBNdMoG8A3VlbT/8vAAD//8ohumCfEAAA
`,
	},

	"/index.html": {
		name:    "index.html",
		local:   "views/index.html",
		size:    817,
		modtime: 1560121981,
		compressed: `
H4sIAAAAAAAC/4SS3WrDMAyF7/sUwrDLxNBr12MwCoMxxvYEaqwmAtcpjlLojN99JO3omv7dBX0nOkeS
U3K05kCgNshB5TwDADCOd1B57LqFqtogFETZkYy0mU9g0RA64K6oKAhFZZeE0keCpcca3rkTo5u5nZ1a
CK48/XXZ9pGKQ+X0WTRt5J82CPp/3oefB7tpLZ4XjkL7gRsyWprr9JPiEBnrO5qXSrgN3aXA6KnpoBmj
TbKtWrc/V6YEEUNNUMJx5w+nOQBnU4JymApyNlrcfeFX633bS/ktEYXqfXmaGHJOCbaRg4B6Ug/bXQUj
7P1tOAo8W4PQRFovlF57rJ/ZLYZ4b6+Qs7LkWIxGa7TnOz76ltH14Jf3SQkouOnGjZ4cyOjxBR7PaLTj
nZ2lRMHl/BsAAP//69LjNjEDAAA=
`,
	},

	"/layout.html": {
		name:    "layout.html",
		local:   "views/layout.html",
		size:    1875,
		modtime: 1560121981,
		compressed: `
H4sIAAAAAAAC/7yVzW7bOBDH73mKMXNdWru3HCwBi6BGC7SHNscgB0Ycy5NQpMAZ2TAMv3tBSXbkLyBo
gp40mo///Dgixe3W4oI8gmpMhWq3uwEAmE1sKGXTICyldkXvSyY446tcoVd7Jxpb3HR29y4kDos5Gmkj
wtyZCh4wrqjEWdbHRsk1ioFyaSKj5KqVhb4bdN/C3tSYK4tcRmqEgldQBi/oJVf3wUsMDjahjbDv+Qsd
GkaGNckSFs5UPIH5/GFyRXpFuG5ClJHumqwsc4sJW3cv/wB5EjJOc2kc5v9N/1XjlTjyrxDR5Ypl45CX
iKJgGXGRq8wwo3DWtBFL7p+6Jj8tmcdM79FI9YvgRZs1cqhx0HgTmWj9SAtwgvDtC9w9FX/GWEWyrCNy
EzzTCnVwVtNF7MkjekuLJ62LM4xKBork+CyUSwxaH3F82jwSgDOb0ApnTBZ1jb4dhvG3BnGR4V0TmGX9
8ezs52A3xc0QsLQCsrnqdU93EPxA34KEqnIIR7xmYLtNDKqTSNZ38q8KSmeYe4dOCxvxHZS/mvq5jRVG
oDL4I/Euhxvji1nWPd7aZmZMuIfvGE7qU2zg6M/Zec6wkNMsnWZFvtqP/1YV8/nDcetDeevO6x2xXGg1
fOfzfBKsVXEYaaYuSaYppr8oJ5BZ5ugDDdK/MCsjGsGrve678Meb3V5fzf8/r8vPstadfNHM0mq8FbrX
C5vBkD+Z/nYrWDfOCEIfhulwv50qHdn9TQMcy1y9cNbS9IVV2pOd/1DRn6fhmHW35HaL3u52vwMAAP//
BbzUglMHAAA=
`,
	},

	"/login.html": {
		name:    "login.html",
		local:   "views/login.html",
		size:    360,
		modtime: 1560121981,
		compressed: `
H4sIAAAAAAAC/2SQUY7yMAyE33sKy+80F2h6if+/QGgMWJvYUeKyQlXvvmrLSrC8JfONRx4vS6QLCwHm
wILr2gEADJHvMKXQmsdJxUgMx53s9KI1/+IyVzptAkKYjFU8uqRXFoRMdtPosWh7HT8imFJsZO/yjljK
bCAhk0fTLxIEexTyWEJr31ojQklhopumSNXj/83T9z2O3WfYeTZTeQa0+ZzZ8G31p+HlfSqVc6gPHP/x
VYBlcAf4U8F9dhjcdonjP7jI97FbFpK4rj8BAAD///JUCoxoAQAA
`,
	},

	"/flag": {
		name:  "flag",
		local: `views/flag`,
		isDir: true,
	},

	"/views": {
		name:  "views",
		local: `./views`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"views/flag": {
		_escData["/flag/create.html"],
		_escData["/flag/show.html"],
	},

	"./views": {
		_escData["/flag"],
		_escData["/index.html"],
		_escData["/layout.html"],
		_escData["/login.html"],
	},
}
