// Code generated by go-swagger; DO NOT EDIT.

package release

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new release API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for release API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateReleaseFlag(params *CreateReleaseFlagParams, authInfo runtime.ClientAuthInfoWriter) (*CreateReleaseFlagOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateReleaseFlag creates a release flag that can be used for managing a feature rollout

  This operation allows you to create a new release flag.
*/
func (a *Client) CreateReleaseFlag(params *CreateReleaseFlagParams, authInfo runtime.ClientAuthInfoWriter) (*CreateReleaseFlagOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateReleaseFlagParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createReleaseFlag",
		Method:             "POST",
		PathPattern:        "/release-flags",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateReleaseFlagReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateReleaseFlagOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createReleaseFlag: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
